# Generated by Django 3.0 on 2021-11-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, unique=True, verbose_name='email')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Full Name')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('address', models.TextField(blank=True, null=True)),
                ('verify_code', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('social_id', models.TextField(blank=True, null=True)),
                ('provider', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active user'), ('inactive', 'User Inactive'), ('deleted', 'Soft Delete user')], default='active', max_length=32)),
            ],
            options={
                'verbose_name_plural': 'users',
            },
        ),
    ]
